### PR TITLE
Add html language attribute

### PR DESCRIPTION
**Pull request by szepeviktor**
I am not sure `if` works on one line.
Please help me.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Can I says `{{- if it.lang }}` to remove that space?

**Comment by szepeviktor** [comment]
> always have a language and fallback to `en`.

Done 🍏

**Comment by oscarotero** [comment]
Thank you!

**Comment by szepeviktor** [comment]
Glad to contribute to your project.

**Pull request merged**
